DROP TABLE USER;
CREATE TABLE USER(
ID NUMBER(3) PRIMARY KEY,
FIRST_NAME TEXT(15),
MIDDLE_NAME TEXT(10),
LAST_NAME TEXT(15),
EMAIL_ID VARCHAR2(15),
ADDRESS VARCHAR2(30),
USERID VARCHAR2(10),
PASSWORD VARCHAR2(15),
);